### ISSUE TITLE
RuntimeError: index_select(): Expected dtype int32 or int64 for index

### ISSUE THREAD

**Issue by kurtabela** [rgwt123/Secoco#1]
Hi,

When I run the following command (inspired from [here](https://github.com/rgwt123/Secoco/blob/443685fab345b4910927e988f0b7b94ccb599a29/scripts_wmt/sacrebleu_repair.sh)):

`cat $DATA_DIR/test.en \
| fairseq-interactive $DATA_OUT --path $CHECKPOINTS/checkpoint_best.pt  -s $SRC_FILE -t $TGT_FILE --beam 5 --remove-bpe --max-tokens 3000 --buffer-size 3000 \
    --max-source-positions 128 --max-target-positions 128 --skip-invalid-size-inputs-valid-test `

I get the following error:

Traceback (most recent call last):
  File "/usr/local/bin/fairseq-interactive", line 8, in <module>
    sys.exit(cli_main())
  File "/usr/local/lib/python3.8/dist-packages/fairseq_cli/interactive.py", line 213, in cli_main
    main(args)
  File "/usr/local/lib/python3.8/dist-packages/fairseq_cli/interactive.py", line 164, in main
    translations = task.inference_step(generator, models, sample)
  File "/usr/local/lib/python3.8/dist-packages/fairseq/tasks/fairseq_task.py", line 352, in inference_step
    return generator.generate(models, sample, prefix_tokens=prefix_tokens)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/fairseq/sequence_generator.py", line 160, in generate
    return self._generate(sample, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/fairseq/sequence_generator.py", line 419, in _generate
    tokens[:, : step + 1] = torch.index_select(
RuntimeError: index_select(): Expected dtype int32 or int64 for index

What version of pytorch are you using? Could this possibly be it?

**Comment by kurtabela** [comment]
Fixed this by downgrading to pytorch version 1.6.0. I also had to change fairseq/fairseq/search.py line 78 due to messing around with the pytorch version, to this:

`beams_buf = torch.floor_divide(indices_buf, vocab_size)`

This looks like it works in my case
